version: '2'
services:
  cluster1:
    build: .
    ports:
      - "6001:3000"
    volumes:
      - .:/src/app
    environment:
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=''
      - SERVER_NAME='ChatServer_server1'
    command: forever server.js
    depends_on:
      - redis
  cluster2:
    build: .
    ports:
      - "6002:3000"
    volumes:
      - .:/src/app
    environment:
      - PORT=3000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - REDIS_PASSWORD=''
      - SERVER_NAME='ChatServer_server2'
    command: forever server.js
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    environment:
      - PORT=6379
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis