version: '2'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
    environment:
      - PORT=${NODE_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT={DB_PORT}
      - DB_PORT={DB_NAME}
      - DEFAULT_CHATSERVER={DEFAULT_CHATSERVER}
    command: forever start server.js